name: Deploy Voilà App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create docs directory
      run: mkdir -p docs
    
    - name: Convert notebook to HTML
      run: |
        jupyter nbconvert --to html webapp_analysis.ipynb --output-dir=docs --template=classic
        
    - name: Copy index.html to docs
      run: cp index.html docs/
      
    - name: Update webapp link in index.html
      run: |
        sed -i 's/webapp_analysis.html/webapp_analysis.html/g' docs/index.html
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
